/* Kurenai OS — labs/oop.js
   C# OOP Architecture Sandbox: drop class blocks on a 2D canvas, set
   access modifiers, draw inheritance lines, and read clean C# as it
   transpiles live in the side window. Layout persists. */
(function () {
  "use strict";
  var el = KOS.ui.el, store = KOS.store;

  var ACCESS = ["public", "private", "protected"];
  var basingFrom = null; // class id awaiting a base-class click

  function model() { return store.state.oop; }
  function byId(id) { return model().classes.find(function (c) { return c.id === id; }); }

  function newClass(x, y) {
    var m = model();
    var c = {
      id: m.nextId++,
      name: "Class" + (m.classes.length + 1),
      abstract: false,
      x: x, y: y,
      fields: [{ acc: "private", type: "int", name: "value" }],
      methods: [{ acc: "public", type: "void", name: "DoWork", virt: "none" }]
    };
    m.classes.push(c);
    store.save();
    return c;
  }

  /* ---------------- transpiler ---------------- */
  function safeIdent(s, fallback) {
    s = String(s || "").replace(/[^A-Za-z0-9_]/g, "");
    if (!s || /^\d/.test(s)) s = fallback;
    return s;
  }
  function defaultReturn(type) {
    switch (type) {
      case "void": return null;
      case "int": case "long": case "byte": return "0";
      case "double": case "float": case "decimal": return "0";
      case "bool": return "false";
      case "string": return "string.Empty";
      case "char": return "' '";
      default: return "default";
    }
  }
  function transpile() {
    var m = model();
    var lines = [];
    lines.push("// Generated by Kurenai OS \u2014 C# OOP Sandbox");
    lines.push("namespace KurenaiOS.Sandbox");
    lines.push("{");
    if (!m.classes.length) {
      lines.push("    // Add a class block to begin.");
    }
    m.classes.forEach(function (c, ci) {
      var name = safeIdent(c.name, "Class" + c.id);
      var base = m.links.find(function (l) { return l.child === c.id; });
      var baseName = base ? safeIdent((byId(base.parent) || {}).name, "Base") : null;
      var head = "    public " + (c.abstract ? "abstract " : "") + "class " + name +
                 (baseName ? " : " + baseName : "");
      lines.push(head);
      lines.push("    {");
      c.fields.forEach(function (f) {
        lines.push("        " + f.acc + " " + safeIdent(f.type, "int") + " " +
          safeIdent(f.name, "field") + ";");
      });
      if (c.fields.length && c.methods.length) lines.push("");
      // constructor
      lines.push("        public " + name + "()");
      lines.push("        {");
      lines.push("        }");
      if (c.methods.length) lines.push("");
      c.methods.forEach(function (mt, i) {
        var mod = mt.virt === "virtual" ? "virtual " : mt.virt === "override" ? "override " : mt.virt === "abstract" ? "abstract " : "";
        var t = safeIdent(mt.type, "void");
        var sig = "        " + mt.acc + " " + mod + t + " " + safeIdent(mt.name, "Method") + "()";
        if (mt.virt === "abstract") {
          lines.push(sig + ";");
        } else {
          lines.push(sig);
          lines.push("        {");
          var ret = defaultReturn(t);
          if (ret) lines.push("            return " + ret + ";");
          lines.push("        }");
        }
        if (i < c.methods.length - 1) lines.push("");
      });
      lines.push("    }");
      if (ci < m.classes.length - 1) lines.push("");
    });
    lines.push("}");
    return lines.join("\n");
  }
  function highlight(code) {
    var esc = KOS.hub.esc(code);
    return esc
      .replace(/(\/\/[^\n]*)/g, '<span class="cs-cm">$1</span>')
      .replace(/\b(namespace|public|private|protected|class|abstract|virtual|override|return|new|default)\b/g, '<span class="cs-kw">$1</span>')
      .replace(/\b(void|int|long|byte|double|float|decimal|bool|string|char)\b/g, '<span class="cs-ty">$1</span>')
      .replace(/\bclass<\/span> (\w+)/g, 'class</span> <span class="cs-cl">$1</span>');
  }

  /* ---------------- view ---------------- */
  var stage, svg, codePre;

  KOS.views.oop = function (main) {
    document.getElementById("tree").classList.add("hidden");
    document.getElementById("cols").classList.add("no-tree");
    basingFrom = null;

    main.appendChild(el("div", { class: "lab-h" }, [
      el("h1", { text: "C# OOP Architecture Sandbox" }),
      el("p", { class: "sub", text: "Drop class blocks, drag them around, set access modifiers, mark methods virtual/override, and click \u201CSet base\u201D then a parent card to draw the inheritance arrow. The C# on the right rewrites itself with every change — straight into Avalonia-ready structure. AQA 7517 · 4.1.2.3" })
    ]));

    var bar = el("div", { class: "lab-controls" });
    bar.appendChild(el("button", { class: "btn primary", text: "+ Add class", onclick: function () {
      var n = model().classes.length;
      addCard(newClass(30 + (n % 3) * 250, 26 + Math.floor(n / 3) * 210));
      refresh();
    }}));
    bar.appendChild(el("button", { class: "btn", text: "Copy C#", onclick: function () {
      var code = transpile();
      if (navigator.clipboard && navigator.clipboard.writeText) {
        navigator.clipboard.writeText(code).then(function () { KOS.ui.toast("C# copied to clipboard."); },
          function () { fallbackCopy(code); });
      } else fallbackCopy(code);
      function fallbackCopy(text) {
        var ta = el("textarea", { style: "position:fixed;opacity:0" });
        ta.value = text;
        document.body.appendChild(ta);
        ta.select();
        try { document.execCommand("copy"); KOS.ui.toast("C# copied to clipboard."); }
        catch (e) { KOS.ui.toast("Copy failed — select the code manually.", true); }
        ta.remove();
      }
    }}));
    bar.appendChild(el("button", { class: "btn gold", text: "Clear sandbox", onclick: function () {
      if (!model().classes.length || confirm("Remove every class block?")) {
        model().classes = []; model().links = []; store.save(); buildStage();
      }
    }}));
    main.appendChild(bar);

    var wrap = el("div", { id: "oop-stage-wrap" });
    stage = el("div", { id: "oop-stage" });
    svg = document.createElementNS("http://www.w3.org/2000/svg", "svg");
    svg.id = "oop-svg";
    var defs = document.createElementNS("http://www.w3.org/2000/svg", "defs");
    defs.innerHTML = '<marker id="tri" viewBox="0 0 12 12" refX="11" refY="6" markerWidth="11" markerHeight="11" orient="auto"><path d="M1,1 L11,6 L1,11 z" fill="none" stroke="#e2b23f" stroke-width="1.6"/></marker>';
    svg.appendChild(defs);
    stage.appendChild(svg);
    wrap.appendChild(stage);

    var codeBox = el("div", { id: "oop-code" });
    codePre = el("pre", {});
    codeBox.appendChild(codePre);
    wrap.appendChild(codeBox);
    main.appendChild(wrap);

    buildStage();

    function buildStage() {
      stage.querySelectorAll(".cls-card").forEach(function (n) { n.remove(); });
      if (!model().classes.length) {
        // seed a tiny inheritance example on first visit
        if (!model().seeded) {
          model().seeded = true;
          var a = newClass(40, 30); a.name = "GameEntity"; a.abstract = true;
          a.fields = [{ acc: "protected", type: "int", name: "health" },
                      { acc: "private", type: "string", name: "id" }];
          a.methods = [{ acc: "public", type: "void", name: "TakeDamage", virt: "virtual" }];
          var b = newClass(330, 150); b.name = "Suspect";
          b.fields = [{ acc: "private", type: "bool", name: "isLying" }];
          b.methods = [{ acc: "public", type: "void", name: "TakeDamage", virt: "override" },
                       { acc: "public", type: "string", name: "Confess", virt: "none" }];
          model().links.push({ child: b.id, parent: a.id });
          store.save();
        }
      }
      model().classes.forEach(addCard);
      refresh();
    }

    function addCard(c) {
      var card = el("div", { class: "cls-card", style: "left:" + c.x + "px;top:" + c.y + "px" });
      card.dataset.cid = c.id;

      var nameIn = el("input", { value: c.name, "aria-label": "Class name", oninput: function () {
        c.name = nameIn.value; store.save(); refresh();
      }});
      var abst = el("span", { class: "abst", title: "Toggle abstract",
        text: c.abstract ? "✦ abstract" : "✧ concrete",
        onclick: function () { c.abstract = !c.abstract; abst.textContent = c.abstract ? "✦ abstract" : "✧ concrete"; store.save(); refresh(); } });
      var head = el("div", { class: "cls-h" }, [
        nameIn, abst,
        el("button", { class: "xbtn", title: "Delete class", text: "✕", onclick: function (e) {
          e.stopPropagation();
          var m = model();
          m.classes = m.classes.filter(function (k) { return k.id !== c.id; });
          m.links = m.links.filter(function (l) { return l.child !== c.id && l.parent !== c.id; });
          store.save();
          card.remove();
          refresh();
        }})
      ]);
      card.appendChild(head);

      var body = el("div", { class: "cls-body" });
      card.appendChild(body);

      function renderMembers() {
        body.innerHTML = "";
        body.appendChild(el("div", { class: "mem-h", text: "Fields" }));
        c.fields.forEach(function (f, i) { body.appendChild(memberRow(f, i, "fields")); });
        body.appendChild(el("div", { class: "mem-h", text: "Methods" }));
        c.methods.forEach(function (mt, i) { body.appendChild(memberRow(mt, i, "methods")); });
      }
      function memberRow(mem, idx, kind) {
        var acc = el("select", { class: "acc", title: "Access modifier" }, ACCESS.map(function (a) {
          return el("option", { value: a, text: a === "public" ? "+" : a === "private" ? "−" : "#" });
        }));
        acc.value = mem.acc;
        acc.onchange = function () { mem.acc = acc.value; store.save(); refresh(); };
        var type = el("input", { value: mem.type, placeholder: "type", title: "Type" });
        type.oninput = function () { mem.type = type.value; store.save(); refresh(); };
        var nm = el("input", { value: mem.name, placeholder: "name", title: "Name" });
        nm.oninput = function () { mem.name = nm.value; store.save(); refresh(); };
        var row = el("div", { class: "member" }, [acc, type, nm,
          el("button", { class: "xbtn", text: "✕", title: "Remove", onclick: function () {
            c[kind].splice(idx, 1); store.save(); renderMembers(); refresh();
          }})
        ]);
        if (kind === "methods") {
          nm.title = "Method name — click ↻ below to cycle virtual/override/abstract";
        }
        return row;
      }
      renderMembers();

      var foot = el("div", { class: "cls-foot" });
      foot.appendChild(el("button", { class: "mini-btn", text: "+ field", onclick: function () {
        c.fields.push({ acc: "private", type: "int", name: "field" + (c.fields.length + 1) });
        store.save(); renderMembers(); refresh();
      }}));
      foot.appendChild(el("button", { class: "mini-btn", text: "+ method", onclick: function () {
        c.methods.push({ acc: "public", type: "void", name: "Method" + (c.methods.length + 1), virt: "none" });
        store.save(); renderMembers(); refresh();
      }}));
      foot.appendChild(el("button", { class: "mini-btn", text: "↻ virt", title: "Cycle the LAST method through none → virtual → override → abstract", onclick: function () {
        if (!c.methods.length) return;
        var mt = c.methods[c.methods.length - 1];
        var cyc = ["none", "virtual", "override", "abstract"];
        mt.virt = cyc[(cyc.indexOf(mt.virt) + 1) % cyc.length];
        KOS.ui.toast(mt.name + " is now " + (mt.virt === "none" ? "plain" : mt.virt) + ".");
        store.save(); refresh();
      }}));
      foot.appendChild(el("button", { class: "mini-btn", text: "⇡ set base", title: "Then click the parent class card", onclick: function (e) {
        e.stopPropagation();
        var m = model();
        var existing = m.links.find(function (l) { return l.child === c.id; });
        if (existing) {
          m.links = m.links.filter(function (l) { return l.child !== c.id; });
          store.save(); refresh();
          KOS.ui.toast("Inheritance removed from " + c.name + ".");
          return;
        }
        basingFrom = c.id;
        document.querySelectorAll(".cls-card").forEach(function (k) {
          k.classList.toggle("basing", +k.dataset.cid !== c.id);
        });
        KOS.ui.toast("Now click the class " + c.name + " should inherit from. (Click ⇡ again to cancel.)");
      }}));
      card.appendChild(foot);

      // click-to-finish inheritance
      card.addEventListener("click", function () {
        if (basingFrom !== null && basingFrom !== c.id) {
          // refuse cycles
          var m = model(), p = c.id, hops = 0;
          while (p !== undefined && hops++ < 50) {
            if (p === basingFrom) { KOS.ui.toast("That would create an inheritance cycle.", true); endBasing(); return; }
            var up = m.links.find(function (l) { return l.child === p; });
            p = up ? up.parent : undefined;
          }
          m.links.push({ child: basingFrom, parent: c.id });
          var childName = (byId(basingFrom) || {}).name;
          store.save();
          KOS.ui.toast(childName + " : " + c.name + " — inheritance drawn.");
          endBasing(); refresh();
        }
      });
      function endBasing() {
        basingFrom = null;
        document.querySelectorAll(".cls-card").forEach(function (k) { k.classList.remove("basing"); });
      }

      // dragging via the header
      head.addEventListener("pointerdown", function (e) {
        if (e.target.tagName === "INPUT" || e.target.tagName === "BUTTON" || e.target.classList.contains("abst")) return;
        e.preventDefault();
        var startX = e.clientX - c.x, startY = e.clientY - c.y;
        function move(ev) {
          c.x = Math.max(0, Math.min(stage.clientWidth - 232, ev.clientX - startX));
          c.y = Math.max(0, Math.min(stage.clientHeight - 80, ev.clientY - startY));
          card.style.left = c.x + "px"; card.style.top = c.y + "px";
          drawLinks();
        }
        function up() {
          document.removeEventListener("pointermove", move);
          document.removeEventListener("pointerup", up);
          store.save();
        }
        document.addEventListener("pointermove", move);
        document.addEventListener("pointerup", up);
      });

      stage.appendChild(card);
    }

    function drawLinks() {
      while (svg.lastChild && svg.lastChild.tagName !== "defs") svg.removeChild(svg.lastChild);
      model().links.forEach(function (l) {
        var c1 = byId(l.child), c2 = byId(l.parent);
        if (!c1 || !c2) return;
        var e1 = stage.querySelector('[data-cid="' + c1.id + '"]');
        var e2 = stage.querySelector('[data-cid="' + c2.id + '"]');
        if (!e1 || !e2) return;
        var x1 = c1.x + e1.offsetWidth / 2, y1 = c1.y;
        var x2 = c2.x + e2.offsetWidth / 2, y2 = c2.y + e2.offsetHeight;
        var path = document.createElementNS("http://www.w3.org/2000/svg", "path");
        var midY = (y1 + y2) / 2;
        path.setAttribute("d", "M" + x1 + "," + y1 + " C" + x1 + "," + midY + " " + x2 + "," + midY + " " + x2 + "," + y2);
        path.setAttribute("stroke", "#e2b23f");
        path.setAttribute("stroke-width", "1.8");
        path.setAttribute("fill", "none");
        path.setAttribute("marker-end", "url(#tri)");
        svg.appendChild(path);
      });
    }

    function refresh() {
      drawLinks();
      codePre.innerHTML = highlight(transpile());
    }
  };
})();
