/* tools/gen_legacy_classes.js — freeze the legacy class vocabulary (UI rebuild M2).

   Writes tools/ui-legacy-classes.json: every class the legacy stylesheet
   css/main.css selected, which smoke55 then bans from every rebuilt file.
   main.css is deleted in M2, so the source is read from a Git revision —
   the manifest stays reproducible after the file is gone:

     node tools/gen_legacy_classes.js                 (revision HEAD)
     node tools/gen_legacy_classes.js --rev e1e5c65   (any revision)

   Classes are taken from rule preludes only (selectors, including those
   inside :not()/:is()/:where() and nested @media/@supports blocks), never
   from declarations, comments, strings or url()s.                          */
"use strict";
const fs = require("fs");
const path = require("path");
const { execFileSync } = require("child_process");

const ROOT = path.join(__dirname, "..");
const OUT = path.join(__dirname, "ui-legacy-classes.json");
const i = process.argv.indexOf("--rev");
const rev = i === -1 ? "HEAD" : process.argv[i + 1];

const commit = execFileSync("git", ["rev-parse", "--short", rev], { cwd: ROOT, encoding: "utf8" }).trim();
const css = execFileSync("git", ["show", rev + ":css/main.css"], { cwd: ROOT, encoding: "utf8", maxBuffer: 64 << 20 });

function classesOf(source) {
  const text = source
    .replace(/\/\*[\s\S]*?\*\//g, " ")
    .replace(/"(?:\\.|[^"\\])*"|'(?:\\.|[^'\\])*'/g, '""')
    .replace(/url\([^)]*\)/g, "url()");
  const out = new Set();
  let prelude = "";
  for (const ch of text) {
    if (ch === "{") {
      const p = prelude.trim();
      if (p && !p.startsWith("@")) {
        /* a selector list; attribute brackets cannot hold a class */
        for (const m of p.replace(/\[[^\]]*\]/g, "").matchAll(/\.(-?[_a-zA-Z][\w-]*)/g)) out.add(m[1]);
      }
      prelude = "";
    } else if (ch === "}" || ch === ";") prelude = "";
    else prelude += ch;
  }
  return [...out].sort();
}

const classes = classesOf(css);
const manifest = {
  about: "Every class the legacy stylesheet css/main.css selected, frozen before M2 deleted it. " +
    "smoke55 bans these names from rebuilt files (docs/ui-rebuild/PLAN.md §2.1.3). Generated by tools/gen_legacy_classes.js; do not edit.",
  source: "css/main.css",
  revision: commit,
  count: classes.length,
  classes
};
fs.writeFileSync(OUT, JSON.stringify(manifest, null, 1) + "\n");
console.log(`${classes.length} legacy classes from css/main.css@${commit} → ${path.relative(process.cwd(), OUT)}`);
